workspace:
    base: /go
    path: src/github.com/SierraSoftworks/drone-sentry

pipeline:
    publish:docker:
        image: plugins/docker
        repo: sierrasoftworks/drone-sentry
        tag:
            - latest
            - "${DRONE_COMMIT_BRANCH}"
        build_args:
            - "VERSION=${DRONE_COMMIT_SHA}"
        secrets: [ docker_username, docker_password ]